---

- name: Download cfssl bin
  get_url:
    url: https://pkg.cfssl.org/R1.2/{{ item }}_linux-amd64
    dest: /usr/bin/{{ item }}
    mode: 0755
  with_items:
    - cfssl
    - cfssljson
    - cfssl-certinfo
  delegate_to: "{{ groups['masters'][0] }}"

- name: "Make sure /opt/ssl"
  file: path=/opt/ssl state=directory
  delegate_to: "{{ groups['masters'][0] }}"

- name: "Upload config/csr files"
  copy:
    src: "{{ item }}"
    dest: /opt/ssl/{{ item }}
  with_items:
    - config.json
    - csr.json
  when: "inventory_hostname == groups['masters'][0]"

- name: "Create CA"
  shell: "cfssl gencert -initca csr.json | cfssljson -bare ca"
  args:
    chdir: /opt/ssl/
  delegate_to: "{{ groups['masters'][0] }}"
  when: "inventory_hostname == groups['masters'][0]"


- name: "Create CA dirs on all nodes"
  file: path=/etc/kubernetes/ssl/ state=directory

- name: "Upload pem files"
  synchronize: src=/opt/ssl/{{ item }} dest=/etc/kubernetes/ssl/
  with_items:
    - ca.pem
    - ca-key.pem
  delegate_to: "{{ groups['masters'][0] }}"
